### PR TITLE
Started working on the backend

### PR DESCRIPTION
**Pull request by Pknakamura**
Implemented basic backend class initiation function and letter drop function. Also defined the default settings for our game which can be tweaked. Finally also added getters for internal values (not strictly required). Should be good to merge as is.

### CODE REVIEW

**Comment by Pknakamura** [comment]
Looks epic

**Review by bpazner — CHANGES_REQUESTED** [review]
Looks good, but should add comments describing the structure of each function. The comment for the unnecessary function (get_col) should also be removed. Lastly, I think place_piece should currently return 1 if it successfully places a piece (doesn't really matter though if comments explain the return cases).

**Comment by Pknakamura** [comment]
Added comments and used autopep8

**Review by bpazner — APPROVED** [review]
Looks great.

**Pull request merged**
